<nav class="navbar has-shadow" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item is-uppercase is-size-4" href="https://bulma.io">
            Women in Public Service
        </a>
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>
    <div class="navbar-menu">
        <div class="navbar-end">
            <a class="navbar-item is-uppercase">Introduction</a>
            <a class="navbar-item is-uppercase">Share a Story</a>
            <a class="navbar-item is-uppercase">Events</a>
            <a class="navbar-item is-uppercase">About</a>
        </div>
    </div>
</nav>